# Generated by Django 5.2 on 2026-09-28 (hand-written: branch-only models)

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cashier", "0014_drop_redundant_tenant_indexes"),
        ("requests", "0066_remove_unused_cross_tenant_fields"),
        ("telegram_approvals", "0006_drop_redundant_indexes"),
        ("tenants", "0026_tenant_payroll_payout_mode"),
        ("wallets", "0006_bankaccount_is_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashWithdrawalConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=False)),
                (
                    "alert_after_days",
                    models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
                ),
                (
                    "alert_repeat_every_days",
                    models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
                ),
                (
                    "alert_hour",
                    models.PositiveSmallIntegerField(
                        default=9,
                        help_text="Hour of day (0–23, Asia/Tashkent) when overdue alerts are dispatched.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert_telegram_chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_withdrawal_alert_configs",
                        to="telegram_approvals.tenanttelegramchat",
                    ),
                ),
                (
                    "card_telegram_chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_withdrawal_card_configs",
                        to="telegram_approvals.tenanttelegramchat",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_withdrawal_config",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_cash_withdrawal_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "cash_withdrawal_configs"},
        ),
        migrations.CreateModel(
            name="CashWithdrawalConfirmer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "config",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmers",
                        to="cash_withdrawals.cashwithdrawalconfig",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_withdrawal_confirmer_rows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cash_withdrawal_confirmers",
                "constraints": [models.UniqueConstraint(fields=("config", "user"), name="cw_confirmer_uniq")],
            },
        ),
        migrations.CreateModel(
            name="CashWithdrawalAlertRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "config",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_recipients",
                        to="cash_withdrawals.cashwithdrawalconfig",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_withdrawal_alert_rows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cash_withdrawal_alert_recipients",
                "constraints": [models.UniqueConstraint(fields=("config", "user"), name="cw_alert_recipient_uniq")],
            },
        ),
        migrations.CreateModel(
            name="CashWithdrawalRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_type", models.CharField(max_length=50)),
                ("payment_purpose", models.CharField(max_length=200)),
                (
                    "config",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="cash_withdrawals.cashwithdrawalconfig",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_withdrawal_rules",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "cash_withdrawal_rules",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("config", "payment_type", "payment_purpose"), name="cw_rule_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CashWithdrawalReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("confirmed", "Подтверждено"),
                            ("closed", "Закрыто без дохода"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_comment", models.TextField(blank=True, default="")),
                ("last_alert_at", models.DateTimeField(blank=True, null=True)),
                ("alert_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cash_revenue",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_withdrawal_receipt",
                        to="cashier.cashrevenue",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closed_cash_withdrawal_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_cash_withdrawal_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_withdrawal_receipt",
                        to="requests.request",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_withdrawal_receipts",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_withdrawal_receipts",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "cash_withdrawal_receipts",
                "indexes": [
                    models.Index(fields=["tenant", "status", "created_at"], name="cw_receipt_tnt_status_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="CashWithdrawalMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(choices=[("card", "Карточка"), ("alert", "Предупреждение")], max_length=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receipt",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="cash_withdrawals.cashwithdrawalreceipt",
                    ),
                ),
                (
                    "telegram_message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_withdrawal_message",
                        to="telegram_approvals.telegrammessage",
                    ),
                ),
            ],
            options={
                "db_table": "cash_withdrawal_messages",
                "indexes": [models.Index(fields=["receipt", "kind"], name="cw_message_receipt_kind_idx")],
            },
        ),
    ]
