# Generated by Django 5.2.12 on 2026-04-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_tenantuserpreference'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantuserpreference',
            new_name='tenants_ten_tenant__9191d4_idx',
            old_name='tenants_ten_tenant__4a2a66_idx',
        ),
    ]
