# Generated by Django 5.2.14 on 2026-08-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0024_drop_redundant_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='create_payment_request_on_payroll_accrual',
            field=models.BooleanField(default=False),
        ),
    ]
