# Generated by Django 5.2 on 2026-09-24 (hand-written: branch-only field)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0025_tenant_create_payment_request_on_payroll_accrual"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="payroll_payout_mode",
            field=models.CharField(
                choices=[("portal", "Через портал"), ("legacy", "Как раньше")], default="legacy", max_length=16
            ),
        ),
    ]
