# Generated by Django (manual scaffold) for Cashier module placeholder.
from django.db import migrations, models
import django.db.models.deletion

import apps.modules.cashier.models  # noqa: F401


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashExpense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("currency", models.CharField(blank=True, default="UZS", max_length=10)),
                ("expense_date", models.DateField(blank=True, null=True)),
                ("category", models.CharField(blank=True, default="", max_length=120)),
                ("note", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cash_expenses", to="tenants.tenant")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="CashRevenue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("currency", models.CharField(blank=True, default="UZS", max_length=10)),
                ("revenue_date", models.DateField(blank=True, null=True)),
                ("category", models.CharField(blank=True, default="", max_length=120)),
                ("note", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cash_revenues", to="tenants.tenant")),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]

