# Generated by Django (manual scaffold) to extend CashRevenue mock schema.
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cashier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashrevenue",
            name="received_from",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="cashrevenue",
            name="payment_method",
            field=models.CharField(blank=True, default="cash", max_length=50),
        ),
        migrations.AddField(
            model_name="cashrevenue",
            name="reference_no",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="cashrevenue",
            name="status",
            field=models.CharField(blank=True, default="posted", max_length=30),
        ),
        migrations.AddField(
            model_name="cashrevenue",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]

