from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cashier", "0003_created_by"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
DROP TABLE IF EXISTS cash_expenses CASCADE;
DROP TABLE IF EXISTS cashier_cashexpense CASCADE;

CREATE TABLE cash_expenses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id varchar(20) NOT NULL,
    title varchar(255) NOT NULL DEFAULT '',
    amount numeric(18,2) NOT NULL DEFAULT 0,
    currency varchar(10) NOT NULL DEFAULT 'UZS',
    expense_at timestamptz NOT NULL,
    expense_year integer NOT NULL,
    expense_month smallint NOT NULL,
    expense_day smallint NOT NULL,
    note text NOT NULL DEFAULT '',
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    tenant_id bigint NOT NULL REFERENCES tenants_tenant(id) ON DELETE CASCADE,
    created_by_id bigint NOT NULL REFERENCES accounts_user(id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX cash_expenses_tenant_external_year_uniq
    ON cash_expenses (tenant_id, external_id, expense_year);
CREATE INDEX cash_exp_tenant_expense_at_idx
    ON cash_expenses (tenant_id, expense_at);
CREATE INDEX cash_exp_year_month_idx
    ON cash_expenses (expense_year, expense_month);
""",
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name="cashexpense",
                    table="cash_expenses",
                ),
                migrations.AlterModelOptions(
                    name="cashexpense",
                    options={"ordering": ["-expense_at", "-created_at"]},
                ),
                migrations.RemoveField(
                    model_name="cashexpense",
                    name="expense_date",
                ),
                migrations.RemoveField(
                    model_name="cashexpense",
                    name="category",
                ),
                migrations.AddField(
                    model_name="cashexpense",
                    name="expense_at",
                    field=models.DateTimeField(default="2026-01-01T00:00:00Z"),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name="cashexpense",
                    name="expense_day",
                    field=models.PositiveSmallIntegerField(default=1),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name="cashexpense",
                    name="expense_month",
                    field=models.PositiveSmallIntegerField(default=1),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name="cashexpense",
                    name="expense_year",
                    field=models.PositiveIntegerField(default=2026),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name="cashexpense",
                    name="external_id",
                    field=models.CharField(default="0", max_length=20),
                    preserve_default=False,
                ),
                migrations.AddConstraint(
                    model_name="cashexpense",
                    constraint=models.UniqueConstraint(
                        fields=("tenant", "external_id", "expense_year"),
                        name="cash_expenses_tenant_external_year_uniq",
                    ),
                ),
                migrations.AddIndex(
                    model_name="cashexpense",
                    index=models.Index(
                        fields=["tenant", "expense_at"],
                        name="cash_exp_tenant_expense_at_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="cashexpense",
                    index=models.Index(
                        fields=["expense_year", "expense_month"],
                        name="cash_exp_year_month_idx",
                    ),
                ),
            ],
        ),
    ]
