# Generated by Django 5.2.12 on 2026-04-04 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0006_cashexpense_vendor'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashexpense',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_expenses', to='wallets.wallet'),
        ),
        migrations.AddField(
            model_name='cashrevenue',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_revenues', to='wallets.wallet'),
        ),
    ]
