server {
    listen 80;
    server_name _;

    # В контейнере статика лежит тут (монтируем STATIC_ROOT)
    location /static/ {
        alias /usr/share/nginx/static/;
        try_files $uri =404;

        # кэширование для статики (можно убрать, но обычно полезно)
        expires 30d;
        add_header Cache-Control "public";
    }

    location / {
        return 404;
    }
}
