server {
  listen 80;
  server_name _;

  location = /app {
    return 301 /app/;
  }

  location /app/ {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /app/index.html;
  }

  location /api/ {
    proxy_pass http://backend_v2:8001;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
