server {
  listen 80;
  listen [::]:80;
  server_name _;

  location ~ ^/(favicon\.ico|favicon-16x16\.png|favicon-32x32\.png|apple-touch-icon\.png|site\.webmanifest)$ {
    root /usr/share/nginx/html;
    try_files $uri =404;
    access_log off;
    add_header Cache-Control "public, max-age=86400";
  }

  location / { return 404; }
}
