# Generated by Django 5.2.12 on 2026-04-04 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_card', '0002_cardrevenue_cash_style_fields'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardexpense',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_expenses', to='wallets.wallet'),
        ),
        migrations.AddField(
            model_name='cardrevenue',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_revenues', to='wallets.wallet'),
        ),
    ]
