# Generated by Django (manual scaffold) to match provided BankExpense schema.
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank_expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bankexpense",
            table="bank_expenses",
        ),
        migrations.RemoveField(model_name="bankexpense", name="amount"),
        migrations.RemoveField(model_name="bankexpense", name="category"),
        migrations.RemoveField(model_name="bankexpense", name="created_at"),
        migrations.RemoveField(model_name="bankexpense", name="currency"),
        migrations.RemoveField(model_name="bankexpense", name="expense_date"),
        migrations.RemoveField(model_name="bankexpense", name="note"),
        migrations.RemoveField(model_name="bankexpense", name="payload"),
        migrations.RemoveField(model_name="bankexpense", name="title"),
        migrations.AddField(model_name="bankexpense", name="row_no", field=models.IntegerField(default=0), preserve_default=False),
        migrations.AddField(model_name="bankexpense", name="doc_date", field=models.DateField(default="2000-01-01"), preserve_default=False),
        migrations.AddField(model_name="bankexpense", name="process_date", field=models.DateField(default="2000-01-01"), preserve_default=False),
        migrations.AddField(model_name="bankexpense", name="doc_no", field=models.CharField(default="", max_length=50), preserve_default=False),
        migrations.AddField(model_name="bankexpense", name="account_name", field=models.CharField(default="", max_length=255), preserve_default=False),
        migrations.AddField(model_name="bankexpense", name="inn", field=models.CharField(blank=True, max_length=20, null=True)),
        migrations.AddField(model_name="bankexpense", name="account_no", field=models.CharField(default="", max_length=34), preserve_default=False),
        migrations.AddField(model_name="bankexpense", name="mfo", field=models.CharField(default="", max_length=10), preserve_default=False),
        migrations.AddField(model_name="bankexpense", name="debit_turnover", field=models.DecimalField(decimal_places=2, default=0, max_digits=18)),
        migrations.AddField(model_name="bankexpense", name="payment_purpose", field=models.TextField(default=""), preserve_default=False),
        migrations.AddConstraint(
            model_name="bankexpense",
            constraint=models.UniqueConstraint(
                fields=("doc_date", "doc_no", "debit_turnover", "payment_purpose"),
                name="uniq_bank_expense_doc_date_doc_no_turnover_purpose",
            ),
        ),
    ]

