# Generated by Django (manual scaffold) to match provided BankRevenue schema.
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank_expenses", "0002_bankexpense_concrete_schema"),
    ]

    operations = [
        migrations.AlterModelTable(name="bankrevenue", table="bank_revenues"),
        migrations.RemoveField(model_name="bankrevenue", name="amount"),
        migrations.RemoveField(model_name="bankrevenue", name="category"),
        migrations.RemoveField(model_name="bankrevenue", name="created_at"),
        migrations.RemoveField(model_name="bankrevenue", name="currency"),
        migrations.RemoveField(model_name="bankrevenue", name="note"),
        migrations.RemoveField(model_name="bankrevenue", name="payload"),
        migrations.RemoveField(model_name="bankrevenue", name="revenue_date"),
        migrations.RemoveField(model_name="bankrevenue", name="title"),
        migrations.RemoveField(model_name="bankrevenue", name="tenant"),
        migrations.AddField(model_name="bankrevenue", name="tenant_subdomain", field=models.SlugField(default="", max_length=60), preserve_default=False),
        migrations.AddField(model_name="bankrevenue", name="row_no", field=models.IntegerField(blank=True, null=True)),
        migrations.AddField(model_name="bankrevenue", name="doc_date", field=models.DateField(default="2000-01-01"), preserve_default=False),
        migrations.AddField(model_name="bankrevenue", name="process_date", field=models.DateField(default="2000-01-01"), preserve_default=False),
        migrations.AddField(model_name="bankrevenue", name="doc_no", field=models.CharField(default="", max_length=50), preserve_default=False),
        migrations.AddField(model_name="bankrevenue", name="account_name", field=models.CharField(default="", max_length=255), preserve_default=False),
        migrations.AddField(model_name="bankrevenue", name="inn", field=models.CharField(default="", max_length=20), preserve_default=False),
        migrations.AddField(model_name="bankrevenue", name="account_no", field=models.CharField(default="", max_length=34), preserve_default=False),
        migrations.AddField(model_name="bankrevenue", name="mfo", field=models.CharField(default="", max_length=10), preserve_default=False),
        migrations.AddField(model_name="bankrevenue", name="kredit_turnover", field=models.DecimalField(decimal_places=2, default=0, max_digits=18)),
        migrations.AddField(model_name="bankrevenue", name="payment_purpose", field=models.TextField(default=""), preserve_default=False),
        migrations.AddConstraint(
            model_name="bankrevenue",
            constraint=models.UniqueConstraint(
                fields=("doc_no", "doc_date", "kredit_turnover"),
                name="uniq_bank_revenue_doc_no_doc_date_kredit_turnover",
            ),
        ),
        migrations.RunSQL(
            sql="""
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'bank_expenses_id_seq') THEN
    EXECUTE 'ALTER TABLE bank_revenues ALTER COLUMN id SET DEFAULT nextval(''bank_expenses_id_seq'')';
  END IF;
END$$;
""",
            reverse_sql="""
DO $$
BEGIN
  -- best-effort revert to the table's own sequence if it exists
  IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'bank_revenues_id_seq') THEN
    EXECUTE 'ALTER TABLE bank_revenues ALTER COLUMN id SET DEFAULT nextval(''bank_revenues_id_seq'')';
  END IF;
END$$;
""",
        ),
    ]

