# Generated by Django 5.2.12 on 2026-04-04 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_expenses', '0010_bankrevenue_tenant_required_and_unique'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankexpense',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_expenses', to='wallets.wallet'),
        ),
        migrations.AddField(
            model_name='bankrevenue',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_revenues', to='wallets.wallet'),
        ),
    ]
