# Generated by Django 5.2.14 on 2026-08-18 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_expenses', '0016_drop_redundant_tenant_indexes'),
        ('tenants', '0024_drop_redundant_indexes'),
        ('vendors', '0013_drop_redundant_tenant_index'),
        ('wallets', '0005_drop_redundant_tenant_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bankexpense',
            name='uniq_bank_expense_tenant_doc_date_doc_no_turnover_purpose',
        ),
        migrations.AlterField(
            model_name='bankexpense',
            name='doc_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='bankexpense',
            index=models.Index(fields=['tenant', 'vendor', 'debit_turnover', 'doc_date'], name='bank_exp_vendor_amt_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankexpense',
            constraint=models.UniqueConstraint(condition=models.Q(('doc_no', ''), _negated=True), fields=('tenant', 'doc_date', 'doc_no', 'debit_turnover', 'payment_purpose'), name='uniq_bank_expense_tenant_doc_date_doc_no_turnover_purpose'),
        ),
    ]
