# Generated by Django 5.2.14 on 2026-08-24 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_expenses', '0017_remove_bankexpense_uniq_bank_expense_tenant_doc_date_doc_no_turnover_purpose_and_more'),
        ('tenants', '0025_tenant_create_payment_request_on_payroll_accrual'),
        ('wallets', '0005_drop_redundant_tenant_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bankrevenue',
            name='uniq_bank_revenue_tenant_doc_no_doc_date_kredit_turnover',
        ),
        migrations.AddConstraint(
            model_name='bankrevenue',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', '')), fields=('tenant', 'doc_no', 'doc_date', 'kredit_turnover'), name='uniq_bank_revenue_tenant_doc_no_doc_date_kredit_turnover'),
        ),
    ]
