# Generated by Django 5.2.12 on 2026-04-04 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0011_tenantintegrationconfig_portal_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Основной', max_length=255)),
                ('account_no', models.CharField(blank=True, default='', max_length=34)),
                ('mfo', models.CharField(blank=True, default='', max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts_wallets', to='tenants.tenant')),
            ],
            options={
                'db_table': 'wallets_bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_default_for_currency', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'wallets_cash_registers',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CorporateCardAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('external_ref', models.CharField(blank=True, default='', max_length=128)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_card_accounts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'wallets_corporate_card_accounts',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('corporate_card', 'Corporate card')], max_length=20)),
                ('currency', models.CharField(max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('opening_balance_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='wallets.bankaccount')),
                ('cash_register', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='wallets.cashregister')),
                ('corporate_card_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='wallets.corporatecardaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='tenants.tenant')),
            ],
            options={
                'db_table': 'wallets_wallets',
            },
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('tenant',), name='wallets_bankaccount_one_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='cashregister',
            constraint=models.UniqueConstraint(fields=('tenant', 'currency'), name='wallets_cashreg_tenant_currency_uniq'),
        ),
        migrations.AddConstraint(
            model_name='corporatecardaccount',
            constraint=models.UniqueConstraint(fields=('tenant', 'currency'), name='wallets_corpacct_tenant_currency_uniq'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['tenant', 'wallet_type'], name='wallets_wallet_tenant_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bank_account__isnull', True), ('cash_register__isnull', False), ('corporate_card_account__isnull', True), ('wallet_type', 'cash')), models.Q(('bank_account__isnull', False), ('cash_register__isnull', True), ('corporate_card_account__isnull', True), ('wallet_type', 'bank')), models.Q(('bank_account__isnull', True), ('cash_register__isnull', True), ('corporate_card_account__isnull', False), ('wallet_type', 'corporate_card')), _connector='OR'), name='wallets_wallet_type_fk_alignment'),
        ),
    ]
