# Generated by Django 5.2.13 on 2026-05-02 23:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0009_rename_investment_return_approval_indexes'),
        ('tenants', '0020_tenant_cash_expense_external_id_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='investmentreturnapproval',
            name='invrapp_recipient_idx',
        ),
        migrations.RemoveIndex(
            model_name='investmentreturnapproval',
            name='invrapp_gateway_msg_idx',
        ),
        migrations.AddIndex(
            model_name='investmentreturnapproval',
            index=models.Index(fields=['approver_recipient_id'], name='invrapp_recipient_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentreturnapproval',
            index=models.Index(fields=['gateway_message_id'], name='invrapp_gateway_msg_idx'),
        ),
    ]
