# Generated by Django 5.2.14 on 2026-05-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0018_project_investment_approvals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentapprovalconfigstep',
            name='step_type',
            field=models.CharField(choices=[('serial', 'serial'), ('confirmation', 'confirmation'), ('notification', 'notification')], default='serial', max_length=16),
        ),
        migrations.AlterField(
            model_name='investmentreturnapproval',
            name='step_type',
            field=models.CharField(choices=[('serial', 'serial'), ('confirmation', 'confirmation'), ('notification', 'notification')], default='serial', max_length=16),
        ),
    ]
