# Generated by Django 5.2.13 on 2026-05-22 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0020_invest_notification_config'),
        ('requests', '0046_request_tenant_payment_purpose_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='investnotificationconfig',
            name='overdue_notify_every_days',
            field=models.PositiveIntegerField(default=3, help_text='Notify every N days for overdue unpaid payouts (0 = disabled).'),
        ),
        migrations.AddField(
            model_name='investpayoutschedule',
            name='created_request',
            field=models.OneToOneField(blank=True, help_text='Payment request created from this payout (one-click). Guards against duplicates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invest_payout_schedule', to='requests.request'),
        ),
    ]
