# Generated by Django 5.2.14 on 2026-05-23 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0027_alter_approver_recipient_id_to_char'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investpayoutschedule',
            name='created_request',
        ),
        migrations.AddField(
            model_name='investpayoutschedule',
            name='created_return',
            field=models.OneToOneField(blank=True, help_text='InvestReturn created from this payout (one-click). Guards against duplicates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_schedule', to='investments.investreturn'),
        ),
        migrations.AddField(
            model_name='investpayoutschedule',
            name='recipient',
            field=models.CharField(blank=True, choices=[('инвестор', 'Инвестор'), ('партнер', 'Партнер')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investpayoutschedule',
            name='return_type',
            field=models.CharField(blank=True, choices=[('дивиденды', 'Дивиденды'), ('проценты', 'Проценты'), ('доля_прибыли', 'Доля прибыли'), ('тело_инвестиций', 'Тело инвестиций')], max_length=25, null=True),
        ),
    ]
