# Generated by Django 5.2.14 on 2026-08-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0033_drop_redundant_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CbuExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('usd_uzs_rate', models.DecimalField(decimal_places=6, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cbu_exchange_rates',
                'ordering': ['-date'],
            },
        ),
    ]
