# Generated by Django 5.2.14 on 2026-08-23 10:55

from django.db import migrations


def forwards_archive_existing_invest_return_rates(apps, schema_editor):
    """
    Переносит cbu_usd_uzs_rate из InvestReturn в CbuExchangeRate (по дате), прежде
    чем поле будет удалено — без сетевых запросов, курс уже есть в самих записях.
    """
    InvestReturn = apps.get_model("investments", "InvestReturn")
    CbuExchangeRate = apps.get_model("investments", "CbuExchangeRate")

    existing_dates = set(CbuExchangeRate.objects.values_list("date", flat=True))

    rate_by_date: dict = {}
    qs = (
        InvestReturn.objects.exclude(cbu_usd_uzs_rate__isnull=True)
        .exclude(date__isnull=True)
        .order_by("created_at")
        .values("date", "cbu_usd_uzs_rate")
    )
    for row in qs.iterator(chunk_size=200):
        # Последняя по created_at запись на дату побеждает — ближе к финальному/
        # скорректированному значению курса, чем более ранние записи того же дня.
        rate_by_date[row["date"]] = row["cbu_usd_uzs_rate"]

    for d, rate in rate_by_date.items():
        if d in existing_dates:
            continue
        CbuExchangeRate.objects.create(date=d, usd_uzs_rate=rate)


def noop_reverse(apps, schema_editor):
    """Откат не восстанавливает удалённое поле (данные не удаляются)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0034_cbuexchangerate'),
    ]

    operations = [
        migrations.RunPython(forwards_archive_existing_invest_return_rates, noop_reverse),
        migrations.RemoveField(
            model_name='investreturn',
            name='cbu_usd_uzs_rate',
        ),
    ]
