# Generated by Django 5.2.14 on 2026-08-23 11:45
#
# Безопасно без data-migration: sum_uzs полностью реконструируем из
# sum/currency + CbuExchangeRate.usd_uzs_rate на дату InvestReturn.date
# (тот же курс, что уже заархивирован миграцией 0035). Ничего не теряется —
# см. investments.services.usd_uzs_equivalents.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0035_remove_investreturn_cbu_usd_uzs_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investreturn',
            name='sum_uzs',
        ),
    ]
