# Generated by Django (manual scaffold) for placeholder requests module.
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalRequester",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_key", models.CharField(blank=True, default="", max_length=100)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="requesters", to="tenants.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="PortalRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="requests", to="tenants.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="PortalApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("step", models.IntegerField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("portal_request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="approvals", to="requests.portalrequest")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="approvals", to="tenants.tenant")),
            ],
        ),
    ]

