# Generated by Django (manual scaffold) for Requests module expense linking.
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalrequest",
            name="expense_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portalrequest",
            name="expense_external_url",
            field=models.CharField(default="", max_length=500, blank=True),
        ),
    ]

