# Generated by Django (manual scaffold) to create the concrete `requests` table.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
        ("requests", "0002_expense_fields"),
    ]

    operations = [
        migrations.DeleteModel(name="PortalApproval"),
        migrations.DeleteModel(name="PortalRequester"),
        migrations.DeleteModel(name="PortalRequest"),
        migrations.CreateModel(
            name="Request",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_payer", models.CharField(default="", max_length=100)),
                ("category", models.CharField(default="", max_length=100)),
                ("vendor", models.CharField(default="", max_length=150)),
                ("title", models.CharField(default="", max_length=200)),
                ("description", models.TextField(default="")),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(default="UZS", max_length=10)),
                ("payment_type", models.CharField(default="", max_length=50)),
                ("urgency", models.CharField(default="", max_length=50)),
                ("requester", models.CharField(default="", max_length=100)),
                ("payment_purpose", models.CharField(default="", max_length=200)),
                ("submitted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(default="DRAFT", max_length=50)),
                ("payed_at", models.IntegerField(blank=True, null=True)),
                ("expense_id", models.CharField(blank=True, max_length=20, null=True)),
                ("file_link", models.TextField(blank=True, null=True)),
                ("expense_year", models.IntegerField(blank=True, null=True)),
                ("expense_month", models.IntegerField(blank=True, null=True)),
                ("expense_day", models.IntegerField(blank=True, null=True)),
                ("billing_date", models.DateField()),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="requests", to="tenants.tenant")),
            ],
            options={"db_table": "requests"},
        ),
    ]

