from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("requests", "0011_approval_model_state"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS approvals (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                request_id bigint NOT NULL,
                approver_user_id bigint NOT NULL,
                approver_tg_id bigint NULL,
                message_id bigint NULL,
                message_sent boolean NOT NULL DEFAULT false,
                step integer NOT NULL DEFAULT 1,
                step_type varchar(10) NOT NULL DEFAULT 'serial',
                decision varchar(12) NOT NULL DEFAULT 'pending',
                comment text NULL,
                decided_at timestamp with time zone NULL,
                CONSTRAINT approvals_request_step_approver_user_uniq UNIQUE (request_id, step, approver_user_id),
                CONSTRAINT approvals_request_id_fkey
                    FOREIGN KEY (request_id) REFERENCES requests(id)
                    ON DELETE CASCADE ON UPDATE NO ACTION,
                CONSTRAINT approvals_approver_user_id_fkey
                    FOREIGN KEY (approver_user_id) REFERENCES accounts_user(id)
                    ON DELETE RESTRICT ON UPDATE NO ACTION
            );

            CREATE INDEX IF NOT EXISTS approvals_request_id_idx ON approvals (request_id);
            CREATE INDEX IF NOT EXISTS approvals_decision_idx ON approvals (decision);
            CREATE INDEX IF NOT EXISTS approvals_approver_tg_id_idx ON approvals (approver_tg_id);
            CREATE INDEX IF NOT EXISTS approvals_message_sent_idx ON approvals (message_sent);
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS approvals;
            """,
        ),
    ]
