# Generated by Django 5.2.12 on 2026-03-30 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0017_request_expense_id_widen'),
        ('tenants', '0005_tenant_telegram_otp_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestApprovalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request_approval_config', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_request_approval_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'request_approval_configs',
            },
        ),
        migrations.CreateModel(
            name='RequestApprovalPaymentTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Наличные', 'Наличные'), ('Перечисление', 'Перечисление'), ('Пополнение', 'Пополнение'), ('Платежная карта', 'Платежная карта')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_types', to='requests.requestapprovalconfig')),
            ],
            options={
                'db_table': 'request_approval_payment_type_configs',
            },
        ),
        migrations.CreateModel(
            name='RequestApprovalStepConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('step_type', models.CharField(choices=[('serial', 'serial'), ('payment', 'payment')], default='serial', max_length=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('payment_type_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='requests.requestapprovalpaymenttypeconfig')),
            ],
            options={
                'db_table': 'request_approval_step_configs',
            },
        ),
        migrations.CreateModel(
            name='RequestApprovalStepApproverConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_approval_step_approver_configs', to=settings.AUTH_USER_MODEL)),
                ('step_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='requests.requestapprovalstepconfig')),
            ],
            options={
                'db_table': 'request_approval_step_approver_configs',
            },
        ),
        migrations.CreateModel(
            name='UserRequestApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('step_type', models.CharField(choices=[('serial', 'serial'), ('payment', 'payment')], default='serial', max_length=10)),
                ('decision', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=12)),
                ('comment', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request_approvals', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request_approvals', to='requests.request')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request_approvals', to='tenants.tenant')),
            ],
            options={
                'db_table': 'user_request_approvals',
            },
        ),
        migrations.AddIndex(
            model_name='requestapprovalpaymenttypeconfig',
            index=models.Index(fields=['config', 'payment_type'], name='req_appr_pt_cfg_idx'),
        ),
        migrations.AddIndex(
            model_name='requestapprovalpaymenttypeconfig',
            index=models.Index(fields=['is_enabled'], name='req_appr_pt_enabled_idx'),
        ),
        migrations.AddConstraint(
            model_name='requestapprovalpaymenttypeconfig',
            constraint=models.UniqueConstraint(fields=('config', 'payment_type'), name='req_appr_pt_cfg_uniq'),
        ),
        migrations.AddIndex(
            model_name='requestapprovalstepconfig',
            index=models.Index(fields=['payment_type_config', 'step'], name='req_appr_step_idx'),
        ),
        migrations.AddIndex(
            model_name='requestapprovalstepconfig',
            index=models.Index(fields=['payment_type_config'], name='req_appr_steps_by_pt_idx'),
        ),
        migrations.AddConstraint(
            model_name='requestapprovalstepconfig',
            constraint=models.UniqueConstraint(fields=('payment_type_config', 'step'), name='req_appr_step_uniq'),
        ),
        migrations.AddIndex(
            model_name='requestapprovalstepapproverconfig',
            index=models.Index(fields=['step_config'], name='req_appr_step_approvers_idx'),
        ),
        migrations.AddConstraint(
            model_name='requestapprovalstepapproverconfig',
            constraint=models.UniqueConstraint(fields=('step_config', 'approver_user'), name='req_appr_step_approver_uniq'),
        ),
        migrations.AddIndex(
            model_name='userrequestapproval',
            index=models.Index(fields=['approver_user'], name='user_req_appr_user_idx'),
        ),
        migrations.AddIndex(
            model_name='userrequestapproval',
            index=models.Index(fields=['request'], name='user_req_appr_request_idx'),
        ),
        migrations.AddIndex(
            model_name='userrequestapproval',
            index=models.Index(fields=['decision'], name='user_req_appr_decision_idx'),
        ),
        migrations.AddIndex(
            model_name='userrequestapproval',
            index=models.Index(fields=['tenant'], name='user_req_appr_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='userrequestapproval',
            index=models.Index(fields=['approver_user', 'decision'], name='user_req_appr_udec_idx'),
        ),
        migrations.AddIndex(
            model_name='userrequestapproval',
            index=models.Index(fields=['request', 'step'], name='user_req_appr_request_step_idx'),
        ),
        migrations.AddConstraint(
            model_name='userrequestapproval',
            constraint=models.UniqueConstraint(fields=('approver_user', 'request', 'step'), name='user_req_appr_approver_request_step_uniq'),
        ),
    ]
