# Generated by Django 5.2.12 on 2026-03-30 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0018_requestapprovalconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrequestapproval',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='approval',
            name='approver_tg_from_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['approver_tg_from_id'], name='approvals_tg_from_idx'),
        ),
    ]
