# Generated by Django 5.2.12 on 2026-03-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0019_alter_userrequestapproval_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userrequestapproval',
            table='approvals',
        ),
    ]
