# Generated by Django 5.2.12 on 2026-03-30

from django.db import migrations, models


def _backfill_request_categories(apps, schema_editor):
    Request = apps.get_model("requests", "Request")
    RequestCategory = apps.get_model("requests", "RequestCategory")
    RequestPaymentPurposeConfig = apps.get_model("requests", "RequestPaymentPurposeConfig")

    seen = set()
    rows = []

    for tenant_id, raw_name in Request.objects.values_list("tenant_id", "category"):
        name = (raw_name or "").strip()
        if not tenant_id or not name:
            continue
        key = (tenant_id, name)
        if key in seen:
            continue
        seen.add(key)
        rows.append(RequestCategory(tenant_id=tenant_id, name=name, is_active=True))

    for tenant_id, raw_name in RequestPaymentPurposeConfig.objects.values_list(
        "payment_type_config__config__tenant_id",
        "category",
    ):
        name = (raw_name or "").strip()
        if not tenant_id or not name:
            continue
        key = (tenant_id, name)
        if key in seen:
            continue
        seen.add(key)
        rows.append(RequestCategory(tenant_id=tenant_id, name=name, is_active=True))

    if rows:
        RequestCategory.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0020_alter_userrequestapproval_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="request_categories",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "request_categories",
            },
        ),
        migrations.AddIndex(
            model_name="requestcategory",
            index=models.Index(fields=["tenant", "is_active"], name="req_cat_tenant_active_idx"),
        ),
        migrations.AddIndex(
            model_name="requestcategory",
            index=models.Index(fields=["tenant", "name"], name="req_cat_tenant_name_idx"),
        ),
        migrations.AddConstraint(
            model_name="requestcategory",
            constraint=models.UniqueConstraint(fields=("tenant", "name"), name="request_category_tenant_name_uniq"),
        ),
        migrations.RunPython(_backfill_request_categories, migrations.RunPython.noop),
    ]
