# Generated by Django 5.2.12 on 2026-03-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0021_requestcategory_and_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestformpaymenttypeconfig",
            name="default_company_payer",
            field=models.CharField(default="", max_length=100),
        ),
    ]
