# Generated by Django 5.2.13 on 2026-05-02 23:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0042_rename_approval_gateway_neutral_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='approval',
            name='approvals_appr_rcpt_idx',
        ),
        migrations.RemoveIndex(
            model_name='approval',
            name='approvals_ext_uid_idx',
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['approver_recipient_id'], name='approvals_appr_rcpt_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['approver_external_user_id'], name='approvals_ext_uid_idx'),
        ),
    ]
