# Generated by Django 5.2.14 on 2026-05-26 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_amount_nullable'),
        ('requests', '0051_requestcomment_and_comment_webapp_url'),
        ('tenants', '0022_tenant_mcp_enabled'),
        ('vendors', '0012_drop_legacy_vendor_inn_transfer_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['tenant', 'submitted_at', 'id'], name='req_tenant_submitted_id_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['tenant', 'status', 'submitted_at'], name='req_tnt_stat_submitted_idx'),
        ),
    ]
