# Generated by Django 5.2.14 on 2026-08-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0060_drop_redundant_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='approval',
            name='approvals_message_sent_idx',
        ),
    ]
