# Generated by Django 5.2.14 on 2026-08-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0061_remove_approval_approvals_message_sent_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='expense_ref_target',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('payroll', 'payroll'), ('bank', 'bank'), ('card', 'card'), ('card_revenue', 'card_revenue')], max_length=16, null=True),
        ),
    ]
