# Generated by Django 5.2.17 on 2026-09-11 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0063_userapprovalvacation'),
        ('tenants', '0025_tenant_create_payment_request_on_payroll_accrual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapprovalvacation',
            name='tenant',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_approval_vacations', to='tenants.tenant'),
        ),
    ]
