# Generated by Django 5.2.17 on 2026-09-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0064_alter_userapprovalvacation_tenant'),
        ('requests', '0064_request_wallet_ref'),
    ]

    operations = [
    ]
