# Generated by Django 5.2.14 on 2026-08-23 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_drop_redundant_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolldocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrolldocument',
            name='doc_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollline',
            name='days_fact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollline',
            name='days_plan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollline',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollline',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
