# Generated by Django 5.2.17 on 2026-08-24 19:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payrolldocument_created_by_and_more'),
        ('tenants', '0025_tenant_create_payment_request_on_payroll_accrual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='tenants.tenant')),
            ],
            options={
                'db_table': 'payroll_employees',
            },
        ),
        migrations.AddField(
            model_name='payrollline',
            name='employee_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lines', to='payroll.employee'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('tenant', 'full_name'), name='uniq_employee_tenant_full_name'),
        ),
    ]
