# Generated by Django 5.2 on 2026-09-24 (hand-written: branch-only models)

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashier", "0014_drop_redundant_tenant_indexes"),
        ("payroll", "0005_backfill_employee_from_payrollline"),
        ("tenants", "0026_tenant_payroll_payout_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payrolldocument",
            name="status",
            field=models.CharField(
                choices=[("draft", "Черновик"), ("accepted", "Принято"), ("closed", "Закрыто"), ("cancelled", "Отменено")],
                default="accepted",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="payrolldocument",
            name="source",
            field=models.CharField(choices=[("portal", "Портал"), ("n8n", "n8n")], default="n8n", max_length=16),
        ),
        migrations.AddField(
            model_name="payrolldocument",
            name="payout_mode",
            field=models.CharField(
                choices=[("portal", "Через портал"), ("legacy", "Как раньше")], default="legacy", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="payrolldocument",
            name="period_month",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payrolldocument",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[("salary", "Зарплата"), ("advance", "Аванс"), ("bonus", "Премия")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payrolldocument",
            name="closed_underpaid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payrolldocument",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_payroll_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payrolldocument",
            name="close_comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="PayrollPayout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cash_expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_payouts",
                        to="cashier.cashexpense",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payroll_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="payroll.payrolldocument",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_payouts",
                        to="payroll.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_payouts",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выплата ЗП",
                "verbose_name_plural": "Выплаты ЗП",
                "db_table": "payroll_payouts",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cash_expense", "employee"), name="uniq_payroll_payout_expense_employee"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)), name="payroll_payout_amount_positive"
                    ),
                ],
            },
        ),
    ]
